version: "3"

services:
  node:
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres
      - redis

  react:
    restart: always
    build: ./frontend
    ports:
      - "4100:4100"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - node

  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
