version: "3"

services:
  node:
    restart: always
    container_name: node_app
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis

  react:
    restart: always
    build: ./frontend
    container_name: react_app
    ports:
      - "4100:4100"
    volumes:
      - ./frontend:/app
    depends_on:
      - node_app

  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
