version: "3"

services:
  node_app:
    # restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    volumes: 
      - .:/app
  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
